# Auto-generated by compose2nix.
# Modified to use SOPS for secrets management

{
  pkgs,
  lib,
  config,
  ...
}:

let
  # Model configuration for Morphic
  # Using current OpenAI models (gpt-5.4 series - March 2026)
  # Docs: https://platform.openai.com/docs/models
  modelsJson = pkgs.writeText "morphic-models.json" ''
    {
      "models": [
        {
          "id": "gpt-5.4",
          "name": "GPT-5.4",
          "provider": "OpenAI",
          "providerId": "openai",
          "enabled": true,
          "toolCallType": "native"
        },
        {
          "id": "gpt-5.4-mini",
          "name": "GPT-5.4 Mini",
          "provider": "OpenAI",
          "providerId": "openai",
          "enabled": true,
          "toolCallType": "native"
        },
        {
          "id": "gpt-5.4-nano",
          "name": "GPT-5.4 Nano",
          "provider": "OpenAI",
          "providerId": "openai",
          "enabled": true,
          "toolCallType": "native"
        }
      ]
    }
  '';
in
{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # SOPS Secrets Declaration
  sops.secrets."morphic/OPENAI_API_KEY" = { };
  sops.secrets."morphic/TAVILY_API_KEY" = { };
  sops.secrets."morphic/POSTGRES_PASSWORD" = { };

  # SOPS Templates for environment files (KEY=value format)
  sops.templates."morphic-morphic-env" = {
    content = ''
      OPENAI_API_KEY=${config.sops.placeholder."morphic/OPENAI_API_KEY"}
      TAVILY_API_KEY=${config.sops.placeholder."morphic/TAVILY_API_KEY"}
    '';
  };
  sops.templates."morphic-db-env" = {
    content = ''
      DATABASE_URL=postgresql://morphic:${
        config.sops.placeholder."morphic/POSTGRES_PASSWORD"
      }@morphic-stack-postgres:5432/morphic
      DATABASE_RESTRICTED_URL=postgresql://morphic:${
        config.sops.placeholder."morphic/POSTGRES_PASSWORD"
      }@morphic-stack-postgres:5432/morphic
    '';
  };
  sops.templates."morphic-postgres-env" = {
    content = ''
      POSTGRES_DB=morphic
      POSTGRES_USER=morphic
      POSTGRES_PASSWORD=${config.sops.placeholder."morphic/POSTGRES_PASSWORD"}
    '';
  };

  # Containers
  virtualisation.oci-containers.containers."morphic-stack-morphic" = {
    image = "ghcr.io/miurla/morphic:9b773beb26393f291840d4f3ca714b4b100a471f";
    environment = {
      "ANONYMOUS_USER_ID" = "morphic-anonymous";
      "DATABASE_SSL_DISABLED" = "true";
      "ENABLE_AUTH" = "false";
      "LOCAL_REDIS_URL" = "redis://morphic-stack-redis:6379";
      "MORPHIC_CLOUD_DEPLOYMENT" = "false";
      "SEARCH_API" = "tavily";
    };
    environmentFiles = [
      config.sops.templates."morphic-morphic-env".path
      # Database connection using SOPS secrets
      config.sops.templates."morphic-db-env".path
    ];
    volumes = [
      "${modelsJson}:/app/public/config/models.json:ro"
    ];
    ports = [
      "13000:3000/tcp"
    ];
    dependsOn = [
      "morphic-stack-postgres"
      "morphic-stack-redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=morphic"
      "--network=morphic-stack_default"
    ];
  };
  systemd.services."docker-morphic-stack-morphic" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-morphic-stack_default.service"
    ];
    requires = [
      "docker-network-morphic-stack_default.service"
    ];
    partOf = [
      "docker-compose-morphic-stack-root.target"
    ];
    wantedBy = [
      "docker-compose-morphic-stack-root.target"
    ];
  };
  virtualisation.oci-containers.containers."morphic-stack-postgres" = {
    image = "postgres:17-alpine";
    environmentFiles = [
      config.sops.templates."morphic-postgres-env".path
    ];
    volumes = [
      "morphic-stack_postgres_data:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -U morphic"
      "--health-interval=10s"
      "--health-retries=5"
      "--health-timeout=5s"
      "--network-alias=postgres"
      "--network=morphic-stack_default"
    ];
  };
  systemd.services."docker-morphic-stack-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-morphic-stack_default.service"
      "docker-volume-morphic-stack_postgres_data.service"
    ];
    requires = [
      "docker-network-morphic-stack_default.service"
      "docker-volume-morphic-stack_postgres_data.service"
    ];
    partOf = [
      "docker-compose-morphic-stack-root.target"
    ];
    wantedBy = [
      "docker-compose-morphic-stack-root.target"
    ];
  };
  virtualisation.oci-containers.containers."morphic-stack-redis" = {
    image = "redis:alpine";
    volumes = [
      "morphic-stack_redis_data:/data:rw"
    ];
    cmd = [
      "redis-server"
      "--appendonly"
      "yes"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=redis"
      "--network=morphic-stack_default"
    ];
  };
  systemd.services."docker-morphic-stack-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-morphic-stack_default.service"
      "docker-volume-morphic-stack_redis_data.service"
    ];
    requires = [
      "docker-network-morphic-stack_default.service"
      "docker-volume-morphic-stack_redis_data.service"
    ];
    partOf = [
      "docker-compose-morphic-stack-root.target"
    ];
    wantedBy = [
      "docker-compose-morphic-stack-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-morphic-stack_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f morphic-stack_default";
    };
    script = ''
      docker network inspect morphic-stack_default || docker network create morphic-stack_default
    '';
    partOf = [ "docker-compose-morphic-stack-root.target" ];
    wantedBy = [ "docker-compose-morphic-stack-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-morphic-stack_postgres_data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect morphic-stack_postgres_data || docker volume create morphic-stack_postgres_data
    '';
    partOf = [ "docker-compose-morphic-stack-root.target" ];
    wantedBy = [ "docker-compose-morphic-stack-root.target" ];
  };
  systemd.services."docker-volume-morphic-stack_redis_data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect morphic-stack_redis_data || docker volume create morphic-stack_redis_data
    '';
    partOf = [ "docker-compose-morphic-stack-root.target" ];
    wantedBy = [ "docker-compose-morphic-stack-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-morphic-stack-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
